sonicnext-dev/MarathonRecomp

- UnleashedRecomp/gpu/rhi/plume_render_interface_types.h
- UnleashedRecomp/gpu/rhi/plume_vulkan.cpp
- UnleashedRecomp/gpu/video.cpp
The way this was implemented was not complete for other render APIs and was also violating Vulkan spec. `VK_FORMAT_A8_UNORM_KHR` can only be used when `VK_KHR_maintenance5` is enabled, or when using Vulkan 1.4. 
Component swizzling can be implemented across all APIs through Plume and is supported on all devices.
> Map A8_UNORM with swizzle

- UnleashedRecomp/gpu/rhi/plume_vulkan.cpp
- UnleashedRecomp/gpu/video.cpp
- UnleashedRecomp/gpu/video.h
Shadows are created as a Texture2D Array of cascades, currently these are being incorrectly created as a volume texture.
> Add support for array textures

- MarathonRecomp/kernel/io/file_system.cpp
- MarathonRecomp/kernel/xdm.h
Add logic to call `SetLastError` on non-Windows, translating from the `errno`. Some known possible error codes here are translated from their POSIX equivalent, and `ERROR_PATH_NOT_FOUND` is used as a fallback for any others.
Fixes crash in some cutscenes when game tries to open an `xma` file that does not exist.
> Set error code when XCreateFileA fails on non-Windows

- MarathonRecomp/gpu/shader/csd_no_tex_vs.hlsl
- MarathonRecomp/gpu/shader/csd_vs.hlsl
- MarathonRecomp/gpu/shader/movie_vs.hlsl
- MarathonRecomp/gpu/video.cpp
Cherry-pick in the commit for half-pixel offset in the vertex shader from Unleashed.
Fixes:
* Half-pixel offset in XenosRecomp not working.
* Alpha ref not working because the shared constants offset in XenosRecomp is wrong without this.
Requires https://github.com/ga2mer/XenosRecomp/pull/1
> Apply half pixel offset in the vertex shader.

- MarathonRecomp/gpu/video.cpp
> Comment out rest of stubbed PipelineCompilerThread

- MarathonRecomp/api/Sonicteam/TitleTask.h
Offset of `m_SelectedIndex` was slightly off from before, leading to the incorrect button being selected.
> Fix title buttons patch.

- MarathonRecomp/gpu/video.cpp
Setting render target to `nullptr` was being ignored because it causes crashes. Turns out the crashes are only because the game constantly sets targets 1-3 to null and they were all being treated as target 0. Simply checking if `index == 0` instead and allowing `nullptr` fixes depth-only rendering.
Fixes issue where shadow map rendering may be cut off due to smaller color target: https://github.com/ga2mer/MarathonRecomp/issues/29
> Fix depth-only rendering.

- MarathonRecomp/gpu/video.cpp
This was specific to Unleashed and is causing stream 1 to get unset for morph shaders.
> Don't treat POSITION1 as index stream.

- MarathonRecompLib/CMakeLists.txt
Adds CMake hints to let the recompilers output status to terminal during recompilation instead of after, so the progress messages are actually useful.
> Let recompiler output status during recompile.

- MarathonRecomp/gpu/video.cpp
* Update plume commit with residency set support for Metal.
* Add new `DEVICE_ADDRESSABLE` flag to upload allocations.
> Update plume with Metal residency sets.

- MarathonRecomp/kernel/xam.cpp
- MarathonRecomp/os/win32/registry_win32.inl
- MarathonRecomp/ui/game_window.cpp
This pull request aims to replace some leftover UnleashedRecomp mentions and calls within the codebase. (I.E within the Registry)
It's unknown if the stuff within this pull request would impact the game in any capacity so it is set up as a draft for now.
> Remove leftover UnleashedRecomp calls when available

- MarathonRecomp/gpu/video.cpp
Make `g_ClipPlane` not cross constant register boundaries on D3D12.
> Update XenosRecomp and shared constants to fix D3D12

- tools/CMakeLists.txt
Should improve compile speeds and XEX load speeds in debug builds.
CI: https://github.com/squidbus/MarathonRecomp/actions/runs/16872333128
> Always optimize included tool submodules.

- MarathonRecomp/gpu/video.cpp
- MarathonRecomp/gpu/video.h
Fixes lighting on Crisis City half pipes: https://github.com/sonicnext-dev/MarathonRecomp/issues/47
Also added some missing new pipeline state to the PSO caching code.
> Handle front face set using cull mode.

- MarathonRecomp/app.cpp
- MarathonRecomp/patches/audio_patches.cpp
* Music attenuation was not taking master volume into account, making music louder than it should be when the master volume is lowered.
* Saving the volume levels to the config was not working properly since again, it did not take into account the master volume adjustment. This is also just broken anyway because of the music attenuation patch overriding whatever music volume you set, so I just removed it completely for now, pending a proper options menu.
> Fix volume config handling.

- MarathonRecomp/gpu/video.cpp
06 does not make use of instancing anywhere, and these checks were causing instability on D3D12.
> Remove instancing apart from primitive workarounds

- MarathonRecomp/patches/audio_patches.cpp
- MarathonRecomp/user/config_def.h
- MarathonRecompLib/config/Marathon.toml
This PR also adds a new config value to fix the power up jingle duration, since it's 15 seconds instead of 20 seconds and cuts off the end of the song.
Closes https://github.com/sonicnext-dev/MarathonRecomp/issues/119.
> Fix power up jingle fading in BGM prematurely at HFR

- MarathonRecomp/patches/player_patches.cpp
This is pretty minor as all it does is add a missing `Config::TailsGauge` check alongside adding some missing whitespace.
> Clean up Tails Gauge fix

- MarathonRecomp/apu/driver/sdl2_driver.cpp
- MarathonRecomp/main.cpp
- MarathonRecomp/ui/game_window.cpp
Outside of the README and mod loader file, which has remained unaltered, all other instances of the mention "Unleashed Recompiled" has now been replaced with the appropriate "Marathon Recompiled" title instead.
This should allow avoiding any potential new conflicts with Unleashed Recompiled for the time being, although the future remains uncertain.
> Rename additional "Unleashed Recompiled" mentions

- MarathonRecomp/patches/misc_patches.cpp
- MarathonRecompLib/config/Marathon.toml
This implements numerous fixes for point lights, making them much more consistent than they are in vanilla. Most lights should no longer intermittently flicker.
This still has a couple of issues with some lights and some stages, likely due to the low per-object light limit. I don't fully understand the algorithm that selects lights yet, so I can't speak as to whether it's a mistake in the implementation, or just the engineer running out of light slots, but the next step will be bumping the per-object point light limit, likely to 8 or 16, as that's what the limit is on the CPU side.
> Point Light Fixes

- MarathonRecomp/patches/fps_patches.cpp
- MarathonRecompLib/config/Marathon.toml
> Fix TPJ Tarzan for HFR

- MarathonRecomp/patches/fps_patches.cpp
- MarathonRecompLib/config/Marathon.toml
> Fix Tropical Jungle swing logs at HFR

- MarathonRecomp/CMakeLists.txt
- MarathonRecomp/gpu/video.cpp
- MarathonRecomp/gpu/video.h
- MarathonRecompLib/CMakeLists.txt
Adds logic for handling conditional survey and conditional rendering states.
When conditional survey is enabled, shaders are given a spec constant telling them to record the number of fragment invocations into a side buffer. When conditional rendering is enabled, this side buffer is used to determine whether to discard fragments.
Additionally, the texture descriptor set max is decreased to 32768, as using the full 65536 was filling the descriptor heap on D3D12 and causing asserts trying to set up the descriptor set for the buffer. I just halved it to still be a nice number since we will never reach that many textures anyway.
Fixes https://github.com/sonicnext-dev/MarathonRecomp/issues/122
> Fix lens flares not being occluded by geometry.
